compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "svara-test-next"
database_id = "64e87a91-37d9-4bf7-9464-d182ec4fa03b"
migrations_dir = "migrations"

[[analytics_engine_datasets]]
binding = "AYD"
dataset = "svara_test_next"
